version: "3.8"

services:
  go:
    container_name: go-c1
    depends_on: 
      - redis
    ports:
      - "3000:3000"
    image: golang:1.14-alpine
    environment:
      TZ: Asia/Singapore
      REDIS_URL: redis://redis:6379
    volumes:
      - "./:/app"
    working_dir: /app
    command: ["go", "run", "main.go"]

  redis:
    container_name: redis-c1
    expose:
      - "6379"
    image: redis:5-alpine
    restart: always
